# Env
log_wandb: False
show_progress: True
save_dataset: False
save_dataloaders: False

# Training
worker: 0
epochs: 1000
train_batch_size: 2048
eval_batch_size: 4096
learner: adam
learning_rate: 0.0001
weight_decay: 0.0001
# clip_grad_norm: { max_norm: 5, norm_type: 2.0 }
clip_grad_norm: { max_norm: 1, norm_type: 2.0 }


loss_type: CE
train_neg_sample_args: ~
valid_neg_sample_args: ~
test_neg_sample_args: ~
# train_neg_sample_args:
# stopping_step: 8 # default 10 for ml, 50 for others
stopping_step: 60 # default 10 for ml, 50 for others
save_step: 10

layer_norm_eps: 1e-8           
initializer_range: 0.01       

# item_attribute: categories
# selected_features: ['categories']
# item_attribute: class
# selected_features: ['class']
item_attribute: categories
selected_features: ['categories']

# Model
model: SASRecF

n_layers: 4
n_heads: 4
hidden_size: 256
inner_size: 1024
pooling_mode: mean


hidden_act: gelu
hidden_dropout_prob: 0.3
attn_dropout_prob: 0.3

aap_weight: 1.0
mip_weight: 0.2

gpu_id: 0
use_gpu: True


eval_only: False
# resume_path: "/Odyssey/private/n23chahb/compet/RecSys-Benchmark/RecBole/saved/SASRecF_ml-100k/SASRecF-Jan-16-2026_03-38-45.pth"
resume_path: ""

enable_amp: False
enable_scaler: False



state: DEBUG
debug_model: True
exp_name: HLLMRecNaw_ml-1m
