
# split
eval_args:
  split: { 'LS': 'valid_and_test' }
  group_by: user
  order: TO
  # mode: full
  mode: { valid: full, test: full }


repeatable: True
metrics: [Recall, MRR, NDCG, Hit, Precision]
# topk: [1,5,10,20,50,100]
topk: [1, 10, 20, 50]

valid_metric: NDCG@10
valid_metric_bigger: True
# eval_batch_size: 1024
eval_batch_size: 4096

loss_decimal_place: 4
metric_decimal_place: 4

# model checkpoint and log config
checkpoint_dir: checkpoints
wandb_project: RecSys-Benchmark
